version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    restart: always
    environment:
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb:inception
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress:inception
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
    depends_on:
      - mariadb
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/scros/data/wordpress'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/scros/data/database'
networks:
  backend:
    driver: bridge
