version: "3.9"

services:
    # web:
    #     build: ./docker/web
    #     ports:
    #      - "5000:5000"
    #     volumes:
    #      - .:/code
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        ports:
          - "3306:3306"
        volumes:
          - "database:/var/lib/mysql"
volumes:
    database:
