version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    restart: always
    environment:
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_CONNECTION=${DB_CONNECTION}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb:inception
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    restart: always
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
volumes:
  wordpress:
  database:
networks:
  backend:
    driver: bridge
