version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    restart: always
    ports:
      - 443:443
    volumes:
      - database:/var/www/html
    networks:
      - backend
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    restart: always
    volumes:
      - database:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
volumes:
  wordpress:
  database:
networks:
  backend:
